//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.BeOrSy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool FileAssociation_CheckOnStartup {
            get {
                return ((bool)(this["FileAssociation_CheckOnStartup"]));
            }
            set {
                this["FileAssociation_CheckOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public int RecentFiles_MaxLength {
            get {
                return ((int)(this["RecentFiles_MaxLength"]));
            }
            set {
                this["RecentFiles_MaxLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxQb3N0Y29kZUxpc3QgVmVyc2lvbj0iMSI+DQogIDxQb3N0Y29kZUl0ZW0+DQogICAgPENvbW1lbnQ+U2llbWVuc3N0YWR0PC9Db21tZW50Pg0KICAgIDxEYXRlSXRlbUNyYXRlZD4yMDI0LTA4LTE3VDIwOjA5OjEwLjEwNzg5NSswMjowMDwvRGF0ZUl0ZW1DcmF0ZWQ+DQogICAgPERhdGVJdGVtRWRpdGVkPjIwMjQtMDgtMTdUMjA6MDk6MTAuMTA5ODQ2NSswMjowMDwvRGF0ZUl0ZW1FZGl0ZWQ+DQogICAgPENvZGVBY3RpdmU+dHJ1ZTwvQ29kZUFjdGl2ZT4NCiAgICA8Q29kZUNpdHk+QmVybGluPC9Db2RlQ2l0eT4NCiAgICA8Q29kZU5hdGlvbj5EZXV0c2NobGFuZDwvQ29kZU5hdGlvbj4NCiAgICA8Q29kZVN0YXRlPkJlcmxpbjwvQ29kZVN0YXRlPg0KICAgIDxDb2RlUG9zdGNvZGU+MTM2Mjc8L0NvZGVQb3N0Y29kZT4NCiAgPC9Qb3N0Y29kZUl0ZW0+DQo8L1Bvc3Rjb2RlTGlzdD4=")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string PostcodeList {
            get {
                return ((string)(this["PostcodeList"]));
            }
            set {
                this["PostcodeList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool AppUpdate_CheckAtStartUp {
            get {
                return ((bool)(this["AppUpdate_CheckAtStartUp"]));
            }
            set {
                this["AppUpdate_CheckAtStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string Startup_DefaultFileOpen {
            get {
                return ((string)(this["Startup_DefaultFileOpen"]));
            }
            set {
                this["Startup_DefaultFileOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd.MM.yyyy")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DateFormat {
            get {
                return ((string)(this["DateFormat"]));
            }
            set {
                this["DateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool ProgressAllowWeightOverride {
            get {
                return ((bool)(this["ProgressAllowWeightOverride"]));
            }
            set {
                this["ProgressAllowWeightOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1;-1;-1;-1;-1")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string LsvSelectPostcodeWidth {
            get {
                return ((string)(this["LsvSelectPostcodeWidth"]));
            }
            set {
                this["LsvSelectPostcodeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1;-1")]
        public string LsvSelectPostcodeOrder {
            get {
                return ((string)(this["LsvSelectPostcodeOrder"]));
            }
            set {
                this["LsvSelectPostcodeOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd.MM.yyyy HH:mm:ss")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DateTimeFormat {
            get {
                return ((string)(this["DateTimeFormat"]));
            }
            set {
                this["DateTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool Startup_DefaultLoadEmptyProject {
            get {
                return ((bool)(this["Startup_DefaultLoadEmptyProject"]));
            }
            set {
                this["Startup_DefaultLoadEmptyProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public int PostcodeListItemsWarning {
            get {
                return ((int)(this["PostcodeListItemsWarning"]));
            }
            set {
                this["PostcodeListItemsWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string DirectoryFile_DefaultPath {
            get {
                return ((string)(this["DirectoryFile_DefaultPath"]));
            }
            set {
                this["DirectoryFile_DefaultPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool ProgressNewSetActualDate {
            get {
                return ((bool)(this["ProgressNewSetActualDate"]));
            }
            set {
                this["ProgressNewSetActualDate"] = value;
            }
        }
    }
}
