//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.BeOrSy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings_AppConst : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_AppConst defaultInstance = ((Settings_AppConst)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_AppConst())));
        
        public static Settings_AppConst Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Changelog.txt")]
        public string AppUpdate_ChangeLog {
            get {
                return ((string)(this["AppUpdate_ChangeLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLKI.Programme.BeOrSy")]
        public string AppUpdate_Name {
            get {
                return ((string)(this["AppUpdate_Name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OliverKind")]
        public string AppUpdate_Owner {
            get {
                return ((string)(this["AppUpdate_Owner"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeOrSy__v{0}__Setup.exe")]
        public string AppUpdate_SetupSearchPattern {
            get {
                return ((string)(this["AppUpdate_SetupSearchPattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csv")]
        public string PostcodeFile_DefaultExtension {
            get {
                return ((string)(this["PostcodeFile_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PostcodeFile_FilterIndex {
            get {
                return ((int)(this["PostcodeFile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSV-Datei (*.csv)|*.csv|Textdatei XML Base64-Encoded (*.txt)|*.txt|XML-Datei (*.x" +
            "ml)|*.xml")]
        public string PostcodeFile_FilterList {
            get {
                return ((string)(this["PostcodeFile_FilterList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeOrSy Database")]
        public string FileAssociation_ExtensionDescription {
            get {
                return ((string)(this["FileAssociation_ExtensionDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeOrSy.Database")]
        public string FileAssociation_ExtensionFile {
            get {
                return ((string)(this["FileAssociation_ExtensionFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project_Symbol.ico")]
        public string FileAssociation_ExtensionIconFile {
            get {
                return ((string)(this["FileAssociation_ExtensionIconFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeOrSy")]
        public string ProjectFile_DefaultExtension {
            get {
                return ((string)(this["ProjectFile_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProjectFile_FilterIndex {
            get {
                return ((int)(this["ProjectFile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Projektdatei (*.BeOrSy)|*.BeOrSy|Alle Dateien (*.*)|*.*")]
        public string ProjectFile_FilterList {
            get {
                return ((string)(this["ProjectFile_FilterList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ProjectFile_VersionCompatibleNative {
            get {
                return ((string)(this["ProjectFile_VersionCompatibleNative"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectFile_VersionCompatibleConvert {
            get {
                return ((string)(this["ProjectFile_VersionCompatibleConvert"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ProjectFile_Version_Actual {
            get {
                return ((string)(this["ProjectFile_Version_Actual"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|")]
        public string RecentFiles_Seperator {
            get {
                return ((string)(this["RecentFiles_Seperator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("309")]
        public int Debug_FormWidthOffset {
            get {
                return ((int)(this["Debug_FormWidthOffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int ProgressWeightWidth {
            get {
                return ((int)(this["ProgressWeightWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".~")]
        public string TempFileExtension {
            get {
                return ((string)(this["TempFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024")]
        public int WriteDataBufferLength {
            get {
                return ((int)(this["WriteDataBufferLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")]
        public string XMLheader {
            get {
                return ((string)(this["XMLheader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PFByb2dyZXNzVGVtcGxhdGVMaXN0Pg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgIDxJZD42PC9JZD4NCiAgI" +
            "CA8Q29tbWVudD48L0NvbW1lbnQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtR" +
            "WRpdGVkIC8+DQogICAgPENvbG9yPiM4MEZGRkY8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUM" +
            "TM6MzM6MzMuNDkxNzUzOSswMjowMDwvRGF0ZT4NCiAgICA8T3JkZXI+MDwvT3JkZXI+DQogICAgPFN0Y" +
            "XRlPjA8L1N0YXRlPg0KICAgIDxUaWx0ZT5Jbml0aWF0aXYgYmV3ZXJiZW48L1RpbHRlPg0KICAgIDxXZ" +
            "WlnaHQ+NjAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJdGVtPg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgI" +
            "DxJZD43PC9JZD4NCiAgICA8Q29tbWVudD48L0NvbW1lbnQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+D" +
            "QogICAgPERhdGVJdGVtRWRpdGVkIC8+DQogICAgPENvbG9yPiM4MEZGRkY8L0NvbG9yPg0KICAgIDxEY" +
            "XRlPjIwMjQtMDgtMTdUMTM6MzM6MzMuNDkxNzUzOSswMjowMDwvRGF0ZT4NCiAgICA8T3JkZXI+MTwvT" +
            "3JkZXI+DQogICAgPFN0YXRlPjA8L1N0YXRlPg0KICAgIDxUaWx0ZT5TdGVsbGVuYXVzc2NocmVpYnVuZ" +
            "yB2b3JoYW5kZW48L1RpbHRlPg0KICAgIDxXZWlnaHQ+NzAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJd" +
            "GVtPg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgIDxJZD44PC9JZD4NCiAgICA8Q29tbWVudD48L0NvbW1lb" +
            "nQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtRWRpdGVkIC8+DQogICAgPENvb" +
            "G9yPiM4MEZGRkY8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUMTM6MzM6MzMuNDkxNzUzOSswM" +
            "jowMDwvRGF0ZT4NCiAgICA8T3JkZXI+MjwvT3JkZXI+DQogICAgPFN0YXRlPjA8L1N0YXRlPg0KICAgI" +
            "DxUaWx0ZT5HZXNjaHJpZWJlbjwvVGlsdGU+DQogICAgPFdlaWdodD44MDA8L1dlaWdodD4NCiAgPC9Qc" +
            "m9ncmVzc0l0ZW0+DQogIDxQcm9ncmVzc0l0ZW0+DQogICAgPElkPjk8L0lkPg0KICAgIDxDb21tZW50P" +
            "jwvQ29tbWVudD4NCiAgICA8RGF0ZUl0ZW1DcmF0ZWQgLz4NCiAgICA8RGF0ZUl0ZW1FZGl0ZWQgLz4NC" +
            "iAgICA8Q29sb3I+IzAwMDBGRjwvQ29sb3I+DQogICAgPERhdGU+MjAyNC0wOC0xN1QxMzozMzozMy40O" +
            "TE3NTM5KzAyOjAwPC9EYXRlPg0KICAgIDxPcmRlcj4zPC9PcmRlcj4NCiAgICA8U3RhdGU+MDwvU3Rhd" +
            "GU+DQogICAgPFRpbHRlPkFiZ2VzZW5kZXQ8L1RpbHRlPg0KICAgIDxXZWlnaHQ+OTAwPC9XZWlnaHQ+D" +
            "QogIDwvUHJvZ3Jlc3NJdGVtPg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgIDxJZD4xMDwvSWQ+DQogICAgP" +
            "ENvbW1lbnQ+PC9Db21tZW50Pg0KICAgIDxEYXRlSXRlbUNyYXRlZCAvPg0KICAgIDxEYXRlSXRlbUVka" +
            "XRlZCAvPg0KICAgIDxDb2xvcj4jMDAwMEZGPC9Db2xvcj4NCiAgICA8RGF0ZT4yMDI0LTA4LTE3VDEzO" +
            "jMzOjMzLjQ5MTc1MzkrMDI6MDA8L0RhdGU+DQogICAgPE9yZGVyPjQ8L09yZGVyPg0KICAgIDxTdGF0Z" +
            "T4wPC9TdGF0ZT4NCiAgICA8VGlsdGU+RWluZ2FuZ3NiZXN0w6R0aWd1bmc8L1RpbHRlPg0KICAgIDxXZ" +
            "WlnaHQ+MTAwMDwvV2VpZ2h0Pg0KICA8L1Byb2dyZXNzSXRlbT4NCiAgPFByb2dyZXNzSXRlbT4NCiAgI" +
            "CA8SWQ+MTE8L0lkPg0KICAgIDxDb21tZW50PjwvQ29tbWVudD4NCiAgICA8RGF0ZUl0ZW1DcmF0ZWQgL" +
            "z4NCiAgICA8RGF0ZUl0ZW1FZGl0ZWQgLz4NCiAgICA8Q29sb3I+I0ZGRkY4MDwvQ29sb3I+DQogICAgP" +
            "ERhdGU+MjAyNC0wOC0xN1QxMzozMzozMy40OTE3NTM5KzAyOjAwPC9EYXRlPg0KICAgIDxPcmRlcj41P" +
            "C9PcmRlcj4NCiAgICA8U3RhdGU+MDwvU3RhdGU+DQogICAgPFRpbHRlPlRlbGVmb25pbnRlcnZpZXc8L" +
            "1RpbHRlPg0KICAgIDxXZWlnaHQ+MTEwMDwvV2VpZ2h0Pg0KICA8L1Byb2dyZXNzSXRlbT4NCiAgPFByb" +
            "2dyZXNzSXRlbT4NCiAgICA8SWQ+MTI8L0lkPg0KICAgIDxDb21tZW50PjwvQ29tbWVudD4NCiAgICA8R" +
            "GF0ZUl0ZW1DcmF0ZWQgLz4NCiAgICA8RGF0ZUl0ZW1FZGl0ZWQgLz4NCiAgICA8Q29sb3I+I0ZGRkY4M" +
            "DwvQ29sb3I+DQogICAgPERhdGU+MjAyNC0wOC0xN1QxMzozMzozMy40OTE3NTM5KzAyOjAwPC9EYXRlP" +
            "g0KICAgIDxPcmRlcj42PC9PcmRlcj4NCiAgICA8U3RhdGU+MDwvU3RhdGU+DQogICAgPFRpbHRlPkFjY" +
            "2Vzc21lbnQgQ2VudGVyPC9UaWx0ZT4NCiAgICA8V2VpZ2h0PjEyMDA8L1dlaWdodD4NCiAgPC9Qcm9nc" +
            "mVzc0l0ZW0+DQogIDxQcm9ncmVzc0l0ZW0+DQogICAgPElkPjEzPC9JZD4NCiAgICA8Q29tbWVudD48L" +
            "0NvbW1lbnQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtRWRpdGVkIC8+DQogI" +
            "CAgPENvbG9yPiNGRkZGODA8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUMTM6MzM6MzMuNDkxN" +
            "zUzOSswMjowMDwvRGF0ZT4NCiAgICA8T3JkZXI+NzwvT3JkZXI+DQogICAgPFN0YXRlPjA8L1N0YXRlP" +
            "g0KICAgIDxUaWx0ZT4xLiBWb3JzdGVsbHVuZ3NnZXNwcsOkY2g8L1RpbHRlPg0KICAgIDxXZWlnaHQ+M" +
            "TMwMDwvV2VpZ2h0Pg0KICA8L1Byb2dyZXNzSXRlbT4NCiAgPFByb2dyZXNzSXRlbT4NCiAgICA8SWQ+M" +
            "TQ8L0lkPg0KICAgIDxDb21tZW50PjwvQ29tbWVudD4NCiAgICA8RGF0ZUl0ZW1DcmF0ZWQgLz4NCiAgI" +
            "CA8RGF0ZUl0ZW1FZGl0ZWQgLz4NCiAgICA8Q29sb3I+I0ZGRkY4MDwvQ29sb3I+DQogICAgPERhdGU+M" +
            "jAyNC0wOC0xN1QxMzozMzozMy40OTI3NTA5KzAyOjAwPC9EYXRlPg0KICAgIDxPcmRlcj44PC9PcmRlc" +
            "j4NCiAgICA8U3RhdGU+MDwvU3RhdGU+DQogICAgPFRpbHRlPjIuIFZvcnN0ZWxsdW5nc2dlc3Byw6Rja" +
            "DwvVGlsdGU+DQogICAgPFdlaWdodD4xNDAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJdGVtPg0KICA8U" +
            "HJvZ3Jlc3NJdGVtPg0KICAgIDxJZD4xNTwvSWQ+DQogICAgPENvbW1lbnQ+PC9Db21tZW50Pg0KICAgI" +
            "DxEYXRlSXRlbUNyYXRlZCAvPg0KICAgIDxEYXRlSXRlbUVkaXRlZCAvPg0KICAgIDxDb2xvcj4jRkZGR" +
            "jgwPC9Db2xvcj4NCiAgICA8RGF0ZT4yMDI0LTA4LTE3VDEzOjMzOjMzLjQ5Mjc1MDkrMDI6MDA8L0Rhd" +
            "GU+DQogICAgPE9yZGVyPjk8L09yZGVyPg0KICAgIDxTdGF0ZT4wPC9TdGF0ZT4NCiAgICA8VGlsdGU+M" +
            "y4gVm9yc3RlbGx1bmdzZ2VzcHLDpGNoPC9UaWx0ZT4NCiAgICA8V2VpZ2h0PjE1MDA8L1dlaWdodD4NC" +
            "iAgPC9Qcm9ncmVzc0l0ZW0+DQogIDxQcm9ncmVzc0l0ZW0+DQogICAgPElkPjE2PC9JZD4NCiAgICA8Q" +
            "29tbWVudD48L0NvbW1lbnQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtRWRpd" +
            "GVkIC8+DQogICAgPENvbG9yPiM4MEZGODA8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUMTM6M" +
            "zM6MzMuNDkyNzUwOSswMjowMDwvRGF0ZT4NCiAgICA8T3JkZXI+MTA8L09yZGVyPg0KICAgIDxTdGF0Z" +
            "T4wPC9TdGF0ZT4NCiAgICA8VGlsdGU+VmVydHJhZ3N2ZXJoYW5kbHVuZzwvVGlsdGU+DQogICAgPFdla" +
            "WdodD4xNjAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJdGVtPg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgI" +
            "DxJZD4xNzwvSWQ+DQogICAgPENvbW1lbnQ+PC9Db21tZW50Pg0KICAgIDxEYXRlSXRlbUNyYXRlZCAvP" +
            "g0KICAgIDxEYXRlSXRlbUVkaXRlZCAvPg0KICAgIDxDb2xvcj4jODBGRjgwPC9Db2xvcj4NCiAgICA8R" +
            "GF0ZT4yMDI0LTA4LTE3VDEzOjMzOjMzLjQ5Mjc1MDkrMDI6MDA8L0RhdGU+DQogICAgPE9yZGVyPjExP" +
            "C9PcmRlcj4NCiAgICA8U3RhdGU+MDwvU3RhdGU+DQogICAgPFRpbHRlPlp1c2FnZTwvVGlsdGU+DQogI" +
            "CAgPFdlaWdodD4xNzAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJdGVtPg0KICA8UHJvZ3Jlc3NJdGVtP" +
            "g0KICAgIDxJZD4xODwvSWQ+DQogICAgPENvbW1lbnQ+PC9Db21tZW50Pg0KICAgIDxEYXRlSXRlbUNyY" +
            "XRlZCAvPg0KICAgIDxEYXRlSXRlbUVkaXRlZCAvPg0KICAgIDxDb2xvcj4jMDA4MDAwPC9Db2xvcj4NC" +
            "iAgICA8RGF0ZT4yMDI0LTA4LTE3VDEzOjMzOjMzLjQ5Mjc1MDkrMDI6MDA8L0RhdGU+DQogICAgPE9yZ" +
            "GVyPjEyPC9PcmRlcj4NCiAgICA8U3RhdGU+MTwvU3RhdGU+DQogICAgPFRpbHRlPkVpbnN0ZWxsdW5nP" +
            "C9UaWx0ZT4NCiAgICA8V2VpZ2h0PjE4MDA8L1dlaWdodD4NCiAgPC9Qcm9ncmVzc0l0ZW0+DQogIDxQc" +
            "m9ncmVzc0l0ZW0+DQogICAgPElkPjE8L0lkPg0KICAgIDxDb21tZW50PjwvQ29tbWVudD4NCiAgICA8R" +
            "GF0ZUl0ZW1DcmF0ZWQgLz4NCiAgICA8RGF0ZUl0ZW1FZGl0ZWQgLz4NCiAgICA8Q29sb3I+I0ZGMDAwM" +
            "DwvQ29sb3I+DQogICAgPERhdGU+MjAyNC0wOC0xN1QxMzozMzozMy40ODc3NjQyKzAyOjAwPC9EYXRlP" +
            "g0KICAgIDxPcmRlcj4xMzwvT3JkZXI+DQogICAgPFN0YXRlPjI8L1N0YXRlPg0KICAgIDxUaWx0ZT5BY" +
            "nNhZ2U8L1RpbHRlPg0KICAgIDxXZWlnaHQ+MTAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJdGVtPg0KI" +
            "CA8UHJvZ3Jlc3NJdGVtPg0KICAgIDxJZD4yPC9JZD4NCiAgICA8Q29tbWVudD48L0NvbW1lbnQ+DQogI" +
            "CAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtRWRpdGVkIC8+DQogICAgPENvbG9yPiNGR" +
            "jAwMDA8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUMTM6MzM6MzMuNDkwNzU2NiswMjowMDwvR" +
            "GF0ZT4NCiAgICA8T3JkZXI+MTQ8L09yZGVyPg0KICAgIDxTdGF0ZT4yPC9TdGF0ZT4NCiAgICA8VGlsd" +
            "GU+WnVyw7xja2dlem9nZW48L1RpbHRlPg0KICAgIDxXZWlnaHQ+MjAwPC9XZWlnaHQ+DQogIDwvUHJvZ" +
            "3Jlc3NJdGVtPg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgIDxJZD4zPC9JZD4NCiAgICA8Q29tbWVudD48L" +
            "0NvbW1lbnQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtRWRpdGVkIC8+DQogI" +
            "CAgPENvbG9yPiNGRjAwMDA8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUMTM6MzM6MzMuNDkwN" +
            "zU2NiswMjowMDwvRGF0ZT4NCiAgICA8T3JkZXI+MTU8L09yZGVyPg0KICAgIDxTdGF0ZT4yPC9TdGF0Z" +
            "T4NCiAgICA8VGlsdGU+VmVyYWx0ZXQ8L1RpbHRlPg0KICAgIDxXZWlnaHQ+MzAwPC9XZWlnaHQ+DQogI" +
            "DwvUHJvZ3Jlc3NJdGVtPg0KICA8UHJvZ3Jlc3NJdGVtPg0KICAgIDxJZD40PC9JZD4NCiAgICA8Q29tb" +
            "WVudD48L0NvbW1lbnQ+DQogICAgPERhdGVJdGVtQ3JhdGVkIC8+DQogICAgPERhdGVJdGVtRWRpdGVkI" +
            "C8+DQogICAgPENvbG9yPiMwMDAwMDA8L0NvbG9yPg0KICAgIDxEYXRlPjIwMjQtMDgtMTdUMTM6MzM6M" +
            "zMuNDkwNzU2NiswMjowMDwvRGF0ZT4NCiAgICA8T3JkZXI+MTY8L09yZGVyPg0KICAgIDxTdGF0ZT4yP" +
            "C9TdGF0ZT4NCiAgICA8VGlsdGU+R2Vrw7xuZGlndCAoQXJiZWl0Z2ViZXIpPC9UaWx0ZT4NCiAgICA8V" +
            "2VpZ2h0PjQwMDwvV2VpZ2h0Pg0KICA8L1Byb2dyZXNzSXRlbT4NCiAgPFByb2dyZXNzSXRlbT4NCiAgI" +
            "CA8SWQ+NTwvSWQ+DQogICAgPENvbW1lbnQ+PC9Db21tZW50Pg0KICAgIDxEYXRlSXRlbUNyYXRlZCAvP" +
            "g0KICAgIDxEYXRlSXRlbUVkaXRlZCAvPg0KICAgIDxDb2xvcj4jMDAwMDAwPC9Db2xvcj4NCiAgICA8R" +
            "GF0ZT4yMDI0LTA4LTE3VDEzOjMzOjMzLjQ5MTc1MzkrMDI6MDA8L0RhdGU+DQogICAgPE9yZGVyPjE3P" +
            "C9PcmRlcj4NCiAgICA8U3RhdGU+MjwvU3RhdGU+DQogICAgPFRpbHRlPkdla8O8bmRpZ3QgKHNlbGJzd" +
            "Ck8L1RpbHRlPg0KICAgIDxXZWlnaHQ+NTAwPC9XZWlnaHQ+DQogIDwvUHJvZ3Jlc3NJdGVtPg0KPC9Qc" +
            "m9ncmVzc1RlbXBsYXRlTGlzdD4=")]
        public string ProgressListDefault {
            get {
                return ((string)(this["ProgressListDefault"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyy-MM-dd@HH-mm-ss")]
        public string DateTimeFormatForFile {
            get {
                return ((string)(this["DateTimeFormatForFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bericht__Bewerbung__{0}__{1}.html")]
        public string Filename_Report_Application {
            get {
                return ((string)(this["Filename_Report_Application"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bericht__Firma__{0}__{1}.html")]
        public string Filename_Report_Company {
            get {
                return ((string)(this["Filename_Report_Company"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bericht__Kontakt__{0}__{1}.html")]
        public string Filename_Report_Contact {
            get {
                return ((string)(this["Filename_Report_Contact"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bericht__Erinnerungen__{0}.html")]
        public string Filename_Report_ReminderList {
            get {
                return ((string)(this["Filename_Report_ReminderList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int ProgressWeightMax {
            get {
                return ((int)(this["ProgressWeightMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("csv")]
        public string CompanyExportFile_DefaultExtension {
            get {
                return ((string)(this["CompanyExportFile_DefaultExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CompanyExportFile_FilterIndex {
            get {
                return ((int)(this["CompanyExportFile_FilterIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CSV-Datei (*.csv)|*.csv|XML-Datei (*.xml)|*.xml")]
        public string CompanyExportFile_FilterList {
            get {
                return ((string)(this["CompanyExportFile_FilterList"]));
            }
        }
    }
}
