//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.BeOrSy.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.BeOrSy.Properties.Stringtable", typeof(Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inkompatible Datei! ähnelt.
        /// </summary>
        internal static string _0x0001c {
            get {
                return ResourceManager.GetString("0x0001c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ist nicht mit dieser Programmversion kompatibel. ähnelt.
        /// </summary>
        internal static string _0x0001m {
            get {
                return ResourceManager.GetString("0x0001m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- Keine Benennung -- ähnelt.
        /// </summary>
        internal static string _0x0002 {
            get {
                return ResourceManager.GetString("0x0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0003c {
            get {
                return ResourceManager.GetString("0x0003c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; konnte nicht geöffnet werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0003m {
            get {
                return ResourceManager.GetString("0x0003m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0004c {
            get {
                return ResourceManager.GetString("0x0004c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt konnte nicht in die Datei &quot;{0}&quot; gespeichert werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0004m {
            get {
                return ResourceManager.GetString("0x0004m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0005c {
            get {
                return ResourceManager.GetString("0x0005c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Lesen der Projektdatei.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0005m {
            get {
                return ResourceManager.GetString("0x0005m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string _0x0006 {
            get {
                return ResourceManager.GetString("0x0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string _0x0007 {
            get {
                return ResourceManager.GetString("0x0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0008c {
            get {
                return ResourceManager.GetString("0x0008c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ist bereits geöffnet und kann nicht erneut geöffnet werden. ähnelt.
        /// </summary>
        internal static string _0x0008m {
            get {
                return ResourceManager.GetString("0x0008m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Projekt ähnelt.
        /// </summary>
        internal static string _0x0009 {
            get {
                return ResourceManager.GetString("0x0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x000Ac {
            get {
                return ResourceManager.GetString("0x000Ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt konnte nicht in die Datei &quot;{0}&quot; gespeichert werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x000Am {
            get {
                return ResourceManager.GetString("0x000Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Öffnet die Datei.
        ///Änderungen an der Datei werden nicht in der Projektdatei gespeichert, sofern die Datei aus der Projektdatei geladen wurde.
        ///Hierzu muss die Datei neu in die Projektdatei gespeichert werden. ähnelt.
        /// </summary>
        internal static string _0x000B {
            get {
                return ResourceManager.GetString("0x000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichert die gewählte Datei in der Projektdatei. ähnelt.
        /// </summary>
        internal static string _0x000C {
            get {
                return ResourceManager.GetString("0x000C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legt eine Verknüpfung zu der gewählten Datei an. ähnelt.
        /// </summary>
        internal static string _0x000D {
            get {
                return ResourceManager.GetString("0x000D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern? ähnelt.
        /// </summary>
        internal static string _0x000Ec {
            get {
                return ResourceManager.GetString("0x000Ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen an Projekt &quot;{0}&quot; vor dem Schließen speichern?
        ///
        ///Ihre Änderungen gehen verloren, wenn Sie diese nicht speichern. ähnelt.
        /// </summary>
        internal static string _0x000Em {
            get {
                return ResourceManager.GetString("0x000Em", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firmen löschen? ähnelt.
        /// </summary>
        internal static string _0x000Fc {
            get {
                return ResourceManager.GetString("0x000Fc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ausgewählten Firmen werden gelöscht.
        ///
        ///Sollten die zugehörigen Ordner ebenfalls gelöscht werden?
        ///
        ///Die Ordner werden erst von der Festplatte gelöscht, wenn Sie das Projekt speichern. Sollten Sie sofortiges Speichern aktiviert haben erfolgt das Löschen der Ordner unverzüglich. ähnelt.
        /// </summary>
        internal static string _0x000Fm {
            get {
                return ResourceManager.GetString("0x000Fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontakte löschen? ähnelt.
        /// </summary>
        internal static string _0x0010c {
            get {
                return ResourceManager.GetString("0x0010c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die ausgewählten Kontakte tatsächlich löschen? ähnelt.
        /// </summary>
        internal static string _0x0010m {
            get {
                return ResourceManager.GetString("0x0010m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Noch keine Id zugewiesen. ähnelt.
        /// </summary>
        internal static string _0x0011 {
            get {
                return ResourceManager.GetString("0x0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dateien löschen? ähnelt.
        /// </summary>
        internal static string _0x0012c {
            get {
                return ResourceManager.GetString("0x0012c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die ausgewählten Dateien tatsächlich löschen? ähnelt.
        /// </summary>
        internal static string _0x0012m {
            get {
                return ResourceManager.GetString("0x0012m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei überschreiben? ähnelt.
        /// </summary>
        internal static string _0x0013c {
            get {
                return ResourceManager.GetString("0x0013c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Datei sind bereits Daten angehangen. Wollen Sie diese überschreiben? ähnelt.
        /// </summary>
        internal static string _0x0013m {
            get {
                return ResourceManager.GetString("0x0013m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim einlesen der Datei! ähnelt.
        /// </summary>
        internal static string _0x0014c {
            get {
                return ResourceManager.GetString("0x0014c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Einlesen der Datei &quot;{0}&quot; ist ein Fehler aufgetreten.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0014m {
            get {
                return ResourceManager.GetString("0x0014m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei öffnen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x0015c {
            get {
                return ResourceManager.GetString("0x0015c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei konnte nicht geöffnet werden.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0015m {
            get {
                return ResourceManager.GetString("0x0015m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse kopiert. ähnelt.
        /// </summary>
        internal static string _0x0016c {
            get {
                return ResourceManager.GetString("0x0016c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Adresse wurde in die Zwischenablage kopiert. ähnelt.
        /// </summary>
        internal static string _0x0016m {
            get {
                return ResourceManager.GetString("0x0016m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ordner konnte nicht gefunden werden. ähnelt.
        /// </summary>
        internal static string _0x0017 {
            get {
                return ResourceManager.GetString("0x0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Reihenfolge der Fortschritte scheint nicht plausibel zu sein.
        ///Bitte prüfen Sie die Reihenfolge aufmerksam und korrigieren Sie diese gegebenenfalls.
        ///
        ///Wenn Sie sehr viele Fortschrittselemente haben wir diese Warnung ebenfalls angezeigt. ähnelt.
        /// </summary>
        internal static string _0x0018 {
            get {
                return ResourceManager.GetString("0x0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Speichern! ähnelt.
        /// </summary>
        internal static string _0x0019c {
            get {
                return ResourceManager.GetString("0x0019c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Speichern in Datei &quot;{0}&quot; ist ein Fehler aufgetreten.
        ///Möglicherweise konnten Ihre Daten nicht gespeichert werden.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0019m {
            get {
                return ResourceManager.GetString("0x0019m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Suchen der Postleitzahlen! ähnelt.
        /// </summary>
        internal static string _0x0020c {
            get {
                return ResourceManager.GetString("0x0020c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Durchsuchen der Postleitzahlen ist ein Fehler aufgetreten.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0020m {
            get {
                return ResourceManager.GetString("0x0020m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Löschen temporärer Dateien! ähnelt.
        /// </summary>
        internal static string _0x0021c {
            get {
                return ResourceManager.GetString("0x0021c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einige temporär angelegte Dateien konnte nicht gelöscht werden.
        ///Wahrscheinlich sind die Dateien noch geöffnet.
        ///
        ///Bitte schließen Sie die Dateien und löschen diese anschließend manuell. ähnelt.
        /// </summary>
        internal static string _0x0021m {
            get {
                return ResourceManager.GetString("0x0021m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe entspricht keiner gültigen E-Mail-Adresse ähnelt.
        /// </summary>
        internal static string _0x0022 {
            get {
                return ResourceManager.GetString("0x0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe entspricht keiner gültigen URL ähnelt.
        /// </summary>
        internal static string _0x0023 {
            get {
                return ResourceManager.GetString("0x0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Eingabe entspricht keinem gültigen Datum. ähnelt.
        /// </summary>
        internal static string _0x0024 {
            get {
                return ResourceManager.GetString("0x0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erinnerungen löschen? ähnelt.
        /// </summary>
        internal static string _0x0025c {
            get {
                return ResourceManager.GetString("0x0025c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die ausgewählten Erinnerungen tatsächlich löschen? ähnelt.
        /// </summary>
        internal static string _0x0025m {
            get {
                return ResourceManager.GetString("0x0025m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Anzeigen der Postleitzahlen wird vorbereitet. ähnelt.
        /// </summary>
        internal static string _0x0026 {
            get {
                return ResourceManager.GetString("0x0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standardordner der bei der Dateiauswahl angezeigt werden soll ähnelt.
        /// </summary>
        internal static string _0x0027 {
            get {
                return ResourceManager.GetString("0x0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Importieren von Postleitzahlen! ähnelt.
        /// </summary>
        internal static string _0x0028c {
            get {
                return ResourceManager.GetString("0x0028c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Importieren von Postleitzahlen aus der Datei &quot;{0}&quot; ist ein Fehler aufgetreten.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0028m {
            get {
                return ResourceManager.GetString("0x0028m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind bereits Postleitzahlendatensätze vorhanden. ähnelt.
        /// </summary>
        internal static string _0x0029c {
            get {
                return ResourceManager.GetString("0x0029c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind bereits Postleitzahlendatensätze vorhanden. Möchten Sie die vorhandenen Datensätze löschen bevor die neuen Postleitzahlen eingelesen werden? ähnelt.
        /// </summary>
        internal static string _0x0029m {
            get {
                return ResourceManager.GetString("0x0029m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sehr viele Elemente zum Anzeigen. ähnelt.
        /// </summary>
        internal static string _0x002Ac {
            get {
                return ResourceManager.GetString("0x002Ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es werden {0} Einträge zur Anzeige ausgewählt. Dies kann sehr lange dauern. Möchten Sie fortfahren? ähnelt.
        /// </summary>
        internal static string _0x002Am {
            get {
                return ResourceManager.GetString("0x002Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Exportieren von Postleitzahlen! ähnelt.
        /// </summary>
        internal static string _0x002Bc {
            get {
                return ResourceManager.GetString("0x002Bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Exportieren von Postleitzahlen in die Datei &quot;{0}&quot; ist ein Fehler aufgetreten.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x002Bm {
            get {
                return ResourceManager.GetString("0x002Bm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahlen importiert. ähnelt.
        /// </summary>
        internal static string _0x002Cc {
            get {
                return ResourceManager.GetString("0x002Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Postleitzahlen wurden erfolgreich aus der Datei &quot;{0}&quot; importiert. ähnelt.
        /// </summary>
        internal static string _0x002Cm {
            get {
                return ResourceManager.GetString("0x002Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahlen exportiert. ähnelt.
        /// </summary>
        internal static string _0x002Dc {
            get {
                return ResourceManager.GetString("0x002Dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Postleitzahlen wurden erfolgreich in die Datei &quot;{0}&quot; exportiert. ähnelt.
        /// </summary>
        internal static string _0x002Dm {
            get {
                return ResourceManager.GetString("0x002Dm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelle Erinnerungen anzeigen? ähnelt.
        /// </summary>
        internal static string _0x002Ec {
            get {
                return ResourceManager.GetString("0x002Ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gibt aktuelle Erinnerungen die noch nicht bestätigt wurden. Möchten Sie diese jetzt anzeigen? ähnelt.
        /// </summary>
        internal static string _0x002Em {
            get {
                return ResourceManager.GetString("0x002Em", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projekt speichern? ähnelt.
        /// </summary>
        internal static string _0x002Fc {
            get {
                return ResourceManager.GetString("0x002Fc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen an Projekt &quot;{0}&quot; vor dem Schließen speichern?
        ///
        ///Ihre Änderungen gehen verloren, wenn Sie diese nicht speichern. ähnelt.
        /// </summary>
        internal static string _0x002Fm {
            get {
                return ResourceManager.GetString("0x002Fm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung, beim Bearbeiten der Gewichtung! ähnelt.
        /// </summary>
        internal static string _0x0030c {
            get {
                return ResourceManager.GetString("0x0030c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Überschreiben der Gewichtung kann unerwartete Effekte haben.
        ///Die Gewichtung wird nicht mehr, beim Verschieben eines Fortschritts, automatisch aktualisiert.
        ///
        ///Überprüfen Sie Ihre Eingaben auf Plausibilität. ähnelt.
        /// </summary>
        internal static string _0x0030m {
            get {
                return ResourceManager.GetString("0x0030m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firmenname ähnelt.
        /// </summary>
        internal static string _0x0031 {
            get {
                return ResourceManager.GetString("0x0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Musterbewerbung ähnelt.
        /// </summary>
        internal static string _0x0032 {
            get {
                return ResourceManager.GetString("0x0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- Nicht möglich -- ähnelt.
        /// </summary>
        internal static string _0x0033 {
            get {
                return ResourceManager.GetString("0x0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortschritte löschen? ähnelt.
        /// </summary>
        internal static string _0x0034c {
            get {
                return ResourceManager.GetString("0x0034c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die ausgewählten Fortschritte tatsächlich löschen? ähnelt.
        /// </summary>
        internal static string _0x0034m {
            get {
                return ResourceManager.GetString("0x0034m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner Umbenannt. ähnelt.
        /// </summary>
        internal static string _0x0035c {
            get {
                return ResourceManager.GetString("0x0035c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Ordner wurden erfolgreich umbenannt. ähnelt.
        /// </summary>
        internal static string _0x0035m {
            get {
                return ResourceManager.GetString("0x0035m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen speichern? ähnelt.
        /// </summary>
        internal static string _0x0036c {
            get {
                return ResourceManager.GetString("0x0036c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor dem Umbenennen der Ordner müssen die Einstellungen gespeichert werden.
        ///Möchte Sie die Einstellungen jetzt speichern? ähnelt.
        /// </summary>
        internal static string _0x0036m {
            get {
                return ResourceManager.GetString("0x0036m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner Umbenannt. ähnelt.
        /// </summary>
        internal static string _0x0037c {
            get {
                return ResourceManager.GetString("0x0037c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte nicht alle Ordner umbenannt werden. Es sind {0} Fehler aufgetreten. ähnelt.
        /// </summary>
        internal static string _0x0037m {
            get {
                return ResourceManager.GetString("0x0037m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Umbenennen! ähnelt.
        /// </summary>
        internal static string _0x0038c {
            get {
                return ResourceManager.GetString("0x0038c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Umbenennen ist ein Fehler aufgetreten, das Umbenennen kann nicht fortgesetzt werden.
        ///
        ///Fehler:
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0038m {
            get {
                return ResourceManager.GetString("0x0038m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Projektordner Festlegen! ähnelt.
        /// </summary>
        internal static string _0x0039c {
            get {
                return ResourceManager.GetString("0x0039c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde noch kein Projektordner festgelegt. Sie müssen einen Projektordner festlegen bevor Sie Ordner für Firmen, Bewerbungen und Berichte erstellen können. ähnelt.
        /// </summary>
        internal static string _0x0039m {
            get {
                return ResourceManager.GetString("0x0039m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern erforderlich! ähnelt.
        /// </summary>
        internal static string _0x003Ac {
            get {
                return ResourceManager.GetString("0x003Ac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die müssen das Projekt speichern bevor der Ordner angelegt werden kann. Möchten Sie das Projekt jetzt speichern? ähnelt.
        /// </summary>
        internal static string _0x003Am {
            get {
                return ResourceManager.GetString("0x003Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standarddatei festgelegt. ähnelt.
        /// </summary>
        internal static string _0x003Bc {
            get {
                return ResourceManager.GetString("0x003Bc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt &quot;{0}&quot; wird ab sofort geöffnet, sobald die Anwendung gestartet wird. ähnelt.
        /// </summary>
        internal static string _0x003Bm {
            get {
                return ResourceManager.GetString("0x003Bm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berichterstellung fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string _0x003Cc {
            get {
                return ResourceManager.GetString("0x003Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Erstellung des Berichtes ist ein Fehler aufgetreten.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x003Cm {
            get {
                return ResourceManager.GetString("0x003Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- Keine Daten -- ähnelt.
        /// </summary>
        internal static string _0x003D {
            get {
                return ResourceManager.GetString("0x003D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue, ungespeicherte Daten. ähnelt.
        /// </summary>
        internal static string _0x003Ec {
            get {
                return ResourceManager.GetString("0x003Ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine oder mehrere Elemente, die zu diesem Bericht gehören, sind neu und noch nicht gespeichert worden. Daher ist die Erstellung des Berichtes nicht möglich.
        ///
        ///Bitte speichern Sie zuerst das Projekt. ähnelt.
        /// </summary>
        internal static string _0x003Em {
            get {
                return ResourceManager.GetString("0x003Em", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undefiniert ähnelt.
        /// </summary>
        internal static string _0x003F {
            get {
                return ResourceManager.GetString("0x003F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewerbungen löschen? ähnelt.
        /// </summary>
        internal static string _0x0040c {
            get {
                return ResourceManager.GetString("0x0040c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ausgewählten Bewerbungen werden gelöscht.
        ///
        ///Sollten die zugehörigen Ordner ebenfalls gelöscht werden?
        ///
        ///Die Ordner werden erst von der Festplatte gelöscht, wenn Sie das Projekt speichern. Sollten Sie sofortiges Speichern aktiviert haben erfolgt das Löschen der Ordner unverzüglich. ähnelt.
        /// </summary>
        internal static string _0x0040m {
            get {
                return ResourceManager.GetString("0x0040m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archivierung abgeschlossen. ähnelt.
        /// </summary>
        internal static string _0x0041c {
            get {
                return ResourceManager.GetString("0x0041c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Automatische Archivierung wurde erfolgreich abgeschlossen. ähnelt.
        /// </summary>
        internal static string _0x0041m {
            get {
                return ResourceManager.GetString("0x0041m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen der Archivierung abgeschlossen. ähnelt.
        /// </summary>
        internal static string _0x0042c {
            get {
                return ResourceManager.GetString("0x0042c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Archivierungen von Bewerbungen wurden aufgehoben. ähnelt.
        /// </summary>
        internal static string _0x0042m {
            get {
                return ResourceManager.GetString("0x0042m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Setzen der Archivierung. ähnelt.
        /// </summary>
        internal static string _0x0043c {
            get {
                return ResourceManager.GetString("0x0043c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Setzen der Archivierung ist ein Fehler aufgetreten.
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0043m {
            get {
                return ResourceManager.GetString("0x0043m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Daten zum Exportieren! ähnelt.
        /// </summary>
        internal static string _0x0044c {
            get {
                return ResourceManager.GetString("0x0044c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In ihrer Auswahl befinden sich keine Daten zum Exportieren. ähnelt.
        /// </summary>
        internal static string _0x0044m {
            get {
                return ResourceManager.GetString("0x0044m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Exportieren! ähnelt.
        /// </summary>
        internal static string _0x0045c {
            get {
                return ResourceManager.GetString("0x0045c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Exportieren der Firmen ist ein Fehler aufgetreten.
        ///
        ///Fehler:
        ///{0} ähnelt.
        /// </summary>
        internal static string _0x0045m {
            get {
                return ResourceManager.GetString("0x0045m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Importieren! ähnelt.
        /// </summary>
        internal static string _0x0046c {
            get {
                return ResourceManager.GetString("0x0046c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Importieren der Firmen aus der Datei &quot;{0}&quot; ist ein Fehler aufgetreten. Es wurden keine Frimen importiert.
        ///
        ///{1} ähnelt.
        /// </summary>
        internal static string _0x0046m {
            get {
                return ResourceManager.GetString("0x0046m", resourceCulture);
            }
        }
    }
}
